# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5a25d0195d7a7dfb38d35545f39fbce11b90e83ad6e6205cbbb1ca2f9666a2eed480eac5b19ddaca09254ff473eda7d21b559166fd68ac58d3708cd2a53d98a

test:
  secret_key_base: 4cf06f63a3d788168b36a1594395c065c166891141ecce972e98818b720d5b1f0312a29345c2730f021ea378b71751b5eefd64750ea0e4ee8ab7d058503283b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
